# This Ingress routes traffic to the gettingstarted-app-svc service.
# It defines two paths: the root path (/) and /test, both directing traffic to port 90 of the service. 
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gettingstarted-todo-ingress
spec:
  rules:
  - host: "gettingstarted-todo.local"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: gettingstarted-app-svc
            port:
              number: 90 
      - path: /test
        pathType: Prefix
        backend:
          service:
           name: gettingstarted-app-svc
            port:
              number: 90            
     